import os
import sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

import time
import hashlib
import shutil
from pathlib import Path
from typing import Tuple, Optional


class OneDrivePublisher:
    """
    Copy a local CSV to a OneDrive for Business *synced* folder and build a SharePoint URL.

    This class does not use Graph/API credentials. It assumes the OneDrive desktop client
    is installed and is syncing a local folder like:
        C:\\Users\\<User>\\OneDrive - AspenTech\\
    so that anything copied under "Documents/PowerBI" will be uploaded automatically.

    Typical workflow:
      1) Provide the local CSV path that was generated by your exporter.
      2) Provide the local OneDrive root (synced folder path).
      3) Call publish() to copy/overwrite the file into "Documents/PowerBI".
      4) The method returns (local_dest_path, sharepoint_url) for immediate use in Power BI.

    Notes:
      - We compute SHA256 to skip copying if the destination already has the same content.
      - We add small retry loops to handle OneDrive file locks while syncing.
      - SharePoint URL is constructed as:
            {sp_base}/{personal_segment}/Documents/PowerBI/{filename}
        e.g. https://asptechinc-my.sharepoint.com/personal/yibo_li_aspentech_com/Documents/PowerBI/issues_with_advice.csv
      - If your tenant uses a different personal segment, pass it via constructor.
    """

    def __init__(
        self,
        csv_src_path: str,
        onedrive_local_root: str,
        *,
        subdir: str = "Documents/PowerBI",
        sharepoint_base: str = "https://asptechinc-my.sharepoint.com",
        personal_segment: str = "personal/yibo_li_aspentech_com",
        overwrite: bool = True,
        max_retries: int = 5,
        retry_wait_sec: float = 0.5
    ) -> None:
        """
        Args:
            csv_src_path: Local CSV produced by your pipeline.
            onedrive_local_root: Local OneDrive sync root, e.g.:
                r"C:\\Users\\<You>\\OneDrive - AspenTech"
            subdir: Subfolder inside OneDrive where the CSV should live.
            sharepoint_base: Your tenant's SharePoint base URL.
            personal_segment: The "personal/..." segment for your account.
            overwrite: Overwrite existing file when content differs.
            max_retries: Max retries when destination is temporarily locked by OneDrive.
            retry_wait_sec: Sleep between retries (seconds).
        """
        self.csv_src_path = Path(csv_src_path)
        self.onedrive_local_root = Path(onedrive_local_root)
        self.subdir = subdir.strip("/\\")
        self.sharepoint_base = sharepoint_base.rstrip("/")
        self.personal_segment = personal_segment.strip("/")

        self.overwrite = overwrite
        self.max_retries = max_retries
        self.retry_wait_sec = retry_wait_sec

    # --------------------------- helper methods ---------------------------

    @staticmethod
    def _sha256(p: Path) -> Optional[str]:
        if not p.exists() or not p.is_file():
            return None
        h = hashlib.sha256()
        with p.open("rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
        return h.hexdigest()

    def _dest_paths(self) -> Tuple[Path, str]:
        """
        Build the local destination path and the SharePoint URL.
        """
        dest_dir = self.onedrive_local_root / self.subdir
        dest_dir.mkdir(parents=True, exist_ok=True)
        dest_path = dest_dir / self.csv_src_path.name

        sp_url = f"{self.sharepoint_base}/{self.personal_segment}/Documents/PowerBI/{self.csv_src_path.name}"
        return dest_path, sp_url

    # ------------------------------ public API ----------------------------
    def publish(self) -> Tuple[str, str]:
        """
        Atomically copy the source CSV into the OneDrive-synced folder and return (local_path, sharepoint_url).

        This improved version uses a temporary file and atomic replace to reduce the chance
        of OneDrive detecting a half-written file during sync. It also updates the modified
        timestamp to help OneDrive recognize the file as “changed.”

        Workflow:
        1) Compute SHA256 hashes of source and destination to skip if identical.
        2) Copy the source CSV to a temporary file in the same directory.
        3) Flush the temporary file to disk (fsync, opened with write handle for Windows).
        4) Atomically replace the destination file with the temp file.
        5) Update the modification time (mtime) to the current time.
        6) Return the local destination path and its SharePoint URL.

        Notes:
        - Atomic replacement (os.replace) avoids partially written files being seen by OneDrive.
        - os.utime bumps the timestamp, which helps OneDrive detect file changes faster.
        - Exponential backoff between retries improves stability when OneDrive holds a file lock.
        - This method only writes to the local synced folder; cloud upload timing depends on
            the OneDrive client and network conditions.

        Raises:
            FileNotFoundError: if the source file or OneDrive root does not exist.
            RuntimeError: if unable to copy after all retries.
        Returns:
            (str, str): Tuple of (local destination path, SharePoint URL).
        """
        if not self.csv_src_path.exists():
            raise FileNotFoundError(f"CSV not found: {self.csv_src_path}")
        if not self.onedrive_local_root.exists():
            raise FileNotFoundError(f"OneDrive root not found: {self.onedrive_local_root}")

        dest_path, sp_url = self._dest_paths()

        src_hash = self._sha256(self.csv_src_path)
        dst_hash = self._sha256(dest_path)
        if src_hash and dst_hash and src_hash == dst_hash:
            return str(dest_path), sp_url

        last_err: Optional[Exception] = None
        backoff = self.retry_wait_sec

        for _ in range(self.max_retries + 1):
            try:
                tmp_path = dest_path.with_suffix(dest_path.suffix + ".tmp")
                # Clean up any stale temp file from a previous failed attempt.
                try:
                    tmp_path.unlink(missing_ok=True)
                except Exception:
                    pass

                # 1) Copy to temp
                shutil.copyfile(self.csv_src_path, tmp_path)

                # 2) Ensure temp is fully flushed to disk.
                #    Use a write handle (append-binary) so fsync works on Windows.
                with open(tmp_path, "ab") as f:
                    f.flush()
                    os.fsync(f.fileno())

                # 3) Atomically replace the destination
                os.replace(tmp_path, dest_path)

                # 4) Bump modified time to "now" to aid change detection
                now = time.time()
                os.utime(dest_path, (now, now))

                return str(dest_path), sp_url

            except Exception as e:
                last_err = e
                time.sleep(backoff)
                backoff = min(backoff * 2, 5.0)  # exponential backoff, cap at 5s

        raise RuntimeError(f"Failed to copy after retries: {last_err}")


if __name__ == "__main__":
    CSV_LOCAL = r"backend/src/outputs/evaluations/HysysEngine.Engine/2025-10-07_174148/issues_with_advice.csv"
    ONEDRIVE_ROOT = r"C:\Users\LIYIB\OneDrive - Aspen Technology, Inc"

    pub = OneDrivePublisher(
        csv_src_path=CSV_LOCAL,
        onedrive_local_root=ONEDRIVE_ROOT,
        subdir="Documents/PowerBI",
        sharepoint_base="https://asptechinc-my.sharepoint.com",
        personal_segment="personal/yibo_li_aspentech_com",
    )

    local_path, web_url = pub.publish()
    print("Copied to:", local_path)
    print("SharePoint URL:", web_url)